### ISSUE TITLE
Basic unittest coverage.

### ISSUE THREAD

**Issue by charlierm** [charliewolf/pynder#1]
Would be good to have some test coverage, just for piece of mind (I'll write some).

**Comment by charliewolf** [comment]
I agree. We need to write a mock for the API though as I think Tinder would block automated unit testing pretty fast. I will start on that.

**Comment by LanchaBasualdo** [comment]
@charliewolf hey thanks for this repository. How should I request a fb token?

**Comment by charliewolf** [comment]
@LanchaBasualdo that isn't related to this github issue but [https://gist.github.com/rtt/10403467#authenticating](try this).

**Comment by LanchaBasualdo** [comment]
sorry,
the page is down

**Comment by charliewolf** [comment]
@LanchaBasualdo Link works for me. It says:

> The easiest way to get this is to go [here](https://www.facebook.com/dialog/oauth?client_id=464891386855067&redirect_uri=https://www.facebook.com/connect/login_success.html&scope=basic_info,email,public_profile,user_about_me,user_activities,user_birthday,user_education_history,user_friends,user_interests,user_likes,user_location,user_photos,user_relationship_details&response_type=token), log in and then pick the auth token out of the URL you are redirected to.
>

**Comment by LanchaBasualdo** [comment]
thanks,
one last question: I'm not being able to setup the setup.py on mac.
how should I do so
I'm getting : `ImportError: No module named pynder`, of course as Im not being able to install the module

**Comment by charliewolf** [comment]
`sudo python setup.py install`

**Comment by LanchaBasualdo** [comment]
thanks

**Comment by delijati** [comment]
There is https://github.com/kevin1024/vcrpy i use it for all my external api mock test.

**Comment by charliewolf** [comment]
@delijati Wow, haven't seen that--very cool. I've been pretty busy but will hopefully find some time to add this.

**Comment by delijati** [comment]
added some tests in push request #42
