### ISSUE TITLE
How can I get a FBTOKEN for tinder?

### ISSUE THREAD

**Issue by filipe3x** [charliewolf/pynder#11]
Do I need a developer account?

Does that account needs to be associated with the facebook account I am using with tinder? (I'm asking this because I don't want to get my personal facebook account banned)

**Comment by charliewolf** [comment]
See [here](https://gist.github.com/rtt/10403467) under "Authenticating".

**Comment by JakeAustwick** [comment]
@charliewolf; This doesn't seem to work me.

URL ends up as: https://www.facebook.com/connect/blank.html#_=_

Page Content:
`Success 
SECURITY WARNING: Please treat the URL above as you would your password and do not share it with anyone. See the Facebook Help Centre for more information.`

Any ideas?

**Comment by charliewolf** [comment]
@JakeAustwick Works for me. It will only display the access token for about a second.
