### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by sidthekidder** [charliewolf/pynder#110]
Even after some googling, I can't really decipher the date format returned in user.birth_date -
`datetime.datetime(1993, 12, 20, 9, 18, 2, 437000, tzinfo=tzutc())`
What is this? It isn't Dec 20th, 1993, because it changed recently and many users have the same format, eg -
`datetime.datetime(1995, 12, 20, 9, 25, 16, 144000, tzinfo=tzutc())`
`datetime.datetime(1995, 12, 20, 9, 25, 16, 146000, tzinfo=tzutc())`
`datetime.datetime(1992, 12, 20, 9, 25, 16, 147000, tzinfo=tzutc())`
are all nearby_users()

**Comment by charliewolf** [comment]
My guess would be that Tinder is obfuscating the real birthday.

**Comment by sidthekidder** [comment]
Damn, there goes my hope of an unexpectd birthday wish.
