### ISSUE TITLE
Couldn't authenticate

### ISSUE THREAD

**Issue by enric1994** [charliewolf/pynder#114]
Hi, in the last months I used a script with Selenium to get the token every 2h.
Yesterday, after a "git pull", I run again my script and got this error:

>  session = pynder.Session(FBID, FBTOKEN)
>   File "/usr/local/lib/python2.7/dist-packages/pynder/session.py", line 13, in __init__
>     self._api.auth(facebook_id, facebook_token)
>   File "/usr/local/lib/python2.7/dist-packages/pynder/api.py", line 27, in auth
>     raise errors.RequestError("Couldn't authenticate")
> pynder.errors.RequestError: Couldn't authenticate

Maybe Tinder API changed?

Thanks

**Comment by VeNoMouS** [comment]
I'm still authenticating fine...

**Comment by wklm** [comment]
@VeNoMouS where did u get "YOUR_FB_TOKEN"?

**Comment by alexdobo** [comment]
See this post: https://gist.github.com/rtt/10403467

and this issue, as it seems to be pretty much the same as your issue: https://github.com/charliewolf/pynder/issues/93

**Comment by VeNoMouS** [comment]
@wklm i got my function from another issue ticket here.. I use the following.. I'd love to give credit where its due but i cant remember who the original author is.

```
import re
import robobrowser

def get_access_token(email, password):
    s = robobrowser.RoboBrowser(user_agent=MOBILE_USER_AGENT, parser="lxml")
    s.open(FB_AUTH)
    ##submit login form##
    f = s.get_form()
    f["pass"] = password
    f["email"] = email
    s.submit_form(f)
    ##click the 'ok' button on the dialog informing you that you have already authenticated with the Tinder app##
    f = s.get_form()
    s.submit_form(f, submit=f.submit_fields['__CONFIRM__'])
    ##get access token from the html response##
    access_token = re.search(r"access_token=([\w\d]+)", s.response.content.decode()).groups()[0]
    #print  s.response.content.decode()
    return access_token
```

**Comment by wklm** [comment]
@alexdobo thx!

@VeNoMouS thanks a lot, it works perfectly! :+1:

**Comment by modulebaan** [comment]
@VeNoMouS 
Thanks! Works amazingly good! This token is valid for 60 days, all the other methods deliver one that's valid for only 1 - 2 hours.

**Comment by winged-wyvern** [comment]
@VeNoMouS Is this methode still working? It used to work just fine but today it started raising the following exception:
`werkzeug.exceptions.BadRequestKeyError: 400: Bad Request`
Is anyone having the same issue?

**Comment by modulebaan** [comment]
Still works here... Make sure that your account has not been banned by Tinder.
Tinder will send you a banned property when logging in, also make sure that the right user agent is used when authenticating with Facebook otherwise Facebook can serve an other type of their login pages.

**Comment by winged-wyvern** [comment]
I just checked that, the account isn't banned. And I think the link is good aswell since it used to work fine and I didn't modify my code.

**Comment by modulebaan** [comment]
Use a Useragent changer addon for your browser and set the useragent to the one in the code above.
Open developer tools of browser on the Console tab
Now surf with your browser to the authenticating URL provided above and after clicking OK you should see the auth token in the console. If not, something is wrong with your FB account in combination with Tinder, I think...

**Comment by winged-wyvern** [comment]
I tried that without changing my browser's user agent and when I click Ok data doesn't load that's why i don't get the token. But i can't figure out why that is happening. 
I tried a different facebook account and nothing changed.

**Comment by modulebaan** [comment]
Facebook uses a filter for the useragents...

**Comment by winged-wyvern** [comment]
So I can't do anything about it?

**Comment by modulebaan** [comment]
Use a useragent spoofer?

**Comment by winged-wyvern** [comment]
I restarted my router and it worked.

**Comment by modulebaan** [comment]
I found out that sometimes Facebook detects this method and flags the account. You need to fill in the securtiy questions when you login normally in Facebook and it works again :) Then you get indeed: 
 werkzeug.exceptions.BadRequestKeyError: 400: Bad Request

**Comment by integrisec** [comment]
I'm getting a 401 no matter what I try. Has the Facebook and Tinder authentication API changed? Is this method still working for everyone?

**Comment by enric1994** [comment]
Hi @integrisec I can confirm that it is working, try the following:

* Sign in to Tinder with your phone to check that you are not banned
* Make sure that you are authenticating with your Facebook email and not with a phone number. If so, create another account and make sure that you use your email

Note that sometimes you get this error message, but you are getting the Facebook token anyway. Don't consider this as an error.
```
Official error: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```
