### ISSUE TITLE
Liking users results in soft ban?

### ISSUE THREAD

**Issue by halalfood** [charliewolf/pynder#119]
It seems that after using the bot for about 30 minutes to like all users nearby, tinder soft-bans the account for a period of 12-24 hours.

No users nearby pop up on the application or through nearby matches in pynder. Even changing the location using Tinder Plus yields no additional users nearby.

**Comment by halalfood** [comment]
It seems that even with Tinder Plus (paid service) - I am receiving a recs exhausted. Do we happen to know the rate limit for retrieving recs?

**Comment by halalfood** [comment]
Error 200: recs exhausted is what it is retrieving.

**Comment by pttomcat** [comment]
happened  to me after 2500 like. got restore 12 hours later after my last like

**Comment by halalfood** [comment]
shouldnt this not happen if you hold a paid account?

**Comment by pttomcat** [comment]
I don't know. I am a paid user and this happened to me as well.
Probably this is a question for tinder ;)

**Comment by KLVN** [comment]
> shouldnt this not happen if you hold a paid account?

Normally there's no liking limit but it's very suspicious to like every single user in your area 😁 You should make random dislikes every 15-20 likes to simulate human behavior.

**Comment by halalfood** [comment]
ill just live with 12 hour soft bans lol
