### ISSUE TITLE
Examples do not work

### ISSUE THREAD

**Issue by MilesWarburton** [charliewolf/pynder#126]
Just installed pynder to have a play, and the examples are falling over. I have the token and id, posts have said that I shouldn't need the id, however not including that returns a 401. I've verified the that my credentials are correct via curl and I'm able to load my own profile...

How are people using this wrapper?

**Comment by taseppa** [comment]
True I have noticed the same that the examples are outdated, front page material is more up-to date. Not sure why you are getting 401, logging with access token works for me.

**Comment by MilesWarburton** [comment]
Do you have a basic example that you could share :)?

**Comment by taseppa** [comment]
Like mentioned the content on front page works:

```
import pynder
session = pynder.Session(facebook_auth_token)
session.matches() # get users you have already been matched with
```

**Comment by MilesWarburton** [comment]
import pynder
facebook_token='#token'
session = pynder.Session(facebook_token)
session.matches()

The length of my token is 181, just to verify that is the right one...

**Comment by taseppa** [comment]
My token is 238 characters, no idea if they are supposed to be same length

**Comment by charliewolf** [comment]
examples should be working in a45e1663efab194b7c7f5137
