### ISSUE TITLE
Reason for removal of facebook_id?

### ISSUE THREAD

**Issue by KevinCooper** [charliewolf/pynder#129]
Why was the facebook_id field removed?  While the following code snippet works when you already have the XAuthToken, logging into Tinder without the XAuthToken requires both the facebook_token and the facebook_id.

```python
    def __init__(self, facebook_token=None, XAuthToken=None, proxies=None):
        if facebook_token is None and XAuthToken is None:
            raise InitializationError("Either XAuth or facebook token must be set")
```

I'm running the Tinder app version 1983, and it appears that during the Facebook-ID is part of the POST parameters.  Reverting commit https://github.com/charliewolf/pynder/commit/cb583a6e5a55b7be0cd9fe4d983d482654021354 seems to fix the problem.

**Comment by charliewolf** [comment]
reverted in 156a97ce9dc6fbb4535d2fc6
