### ISSUE TITLE
How do I query Already liked me

### ISSUE THREAD

**Issue by tredb** [charliewolf/pynder#131]
Hi, can you assist me in calling up users who have already liked me on Tinder?

**Comment by VeNoMouS** [comment]
Poll a couple times for nearby users, if they come up a couple times, most likely they have liked you.

**Comment by tredb** [comment]
which API do i use?

**Comment by Vinz87** [comment]
you can also try my own little project [TndrAssistant](https://github.com/Vinz87/TndrAssistant) which does especially that :)
