### ISSUE TITLE
'generator' object is not subscriptable

### ISSUE THREAD

**Issue by PaulAhuevo** [charliewolf/pynder#134]
Hi, 

user = users[0] gives me the error in the title.
I tried converting the generator into a list, but that also didn't work the way I intended.

Does anyone know how to resolve that issue?

PS:
if session = pynder.Session(facebook_id, facebook_auth_token) doesn't work, try:
session = pynder.Session(facebook_auth_token)
The facebook_id is not need anymore.

**Comment by charliewolf** [comment]
well, yes, it's a generator. try this:

```
import itertools
first_user = next(itertools.islice(users, 1))
```
