### ISSUE TITLE
Couldn't authenticate error

### ISSUE THREAD

**Issue by MichaelGofron** [charliewolf/pynder#135]
Hello all,

I'm trying to open a pynder session getting a facebook user oauth token as illustrated in this answer in stackoverflow: http://stackoverflow.com/questions/3058723/programmatically-getting-an-access-token-for-using-the-facebook-graph-api

I am getting the following error:
Traceback (most recent call last):
  File "thirstBot.py", line 46, in <module>
    session = pynder.Session(facebook_id=FBID, facebook_token=FBTOKEN)
  File "/Users/user/anaconda3/envs/py27/lib/python2.7/site-packages/pynder/session.py", line 13, in __init__
    self._api.auth(facebook_id, facebook_token)
  File "/Users/user/anaconda3/envs/py27/lib/python2.7/site-packages/pynder/api.py", line 27, in auth
    raise errors.RequestError("Couldn't authenticate")
pynder.errors.RequestError: Couldn't authenticate

It seems that I can't properly create a session because I amn't being authenticated properly. Does anyone have any idea why this might be happening?

**Comment by brishtiteveja** [comment]
I'm getting the same error. Passing the facebook id and facebook user token is not opening a session. Any idea what's going wrong. I am using the access token from https://developers.facebook.com/tools/accesstoken/. After clicking the debug button I got the user id and access token. Am I doing anything wrong? Below is the stack trace:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pynder/session.py", line 13, in __init__
    self._api.auth(facebook_id, facebook_token)
  File "/Library/Python/2.7/site-packages/pynder/api.py", line 27, in auth
    raise errors.RequestError("Couldn't authenticate")
pynder.errors.RequestError: Couldn't authenticate

**Comment by brishtiteveja** [comment]
Awesome. I got the solution from another issue. Getting access token from the defined function by the user VeNoMous works.. https://github.com/charliewolf/pynder/issues/114#issuecomment-269386980
Now I can create the session and grab all the hopeful objects. Great. 
However why doesn't the facebook access token generated by (https://developers.facebook.com/tools/accesstoken/) work?

**Comment by MichaelGofron** [comment]
Not sure. I got it working by using charles proxy to intercept requests between tinder and fb and then used the access token there. This is a longer form token so it lasts longer although it's less automatic since you have to inspect the charles proxy to get the access token.
