### ISSUE TITLE
API Change

### ISSUE THREAD

**Issue by KevinCooper** [charliewolf/pynder#137]
When getting a list of recommendations from `"/user/recs"` , the the list of users no longer has "_id" in the base dictionary, but instead is wrapped to look like:
```
{'type': 'user', 'group_matched': False, 'user': {'distance_mi': 4, ..., _id': '550ef60fad4446czzzzzzzzz', ...}}
```
Adding the following line after `for user in users` in session.py seems to fix the problem.
```
user = user['user']
```
Although this leads me to believe there might be a new non-user type.  As such, the above might need another line of checking to ensure that the `'user'` field exists for each item in the recommendation list.

**Comment by halalfood** [comment]
I am also having an issue. 

session.nearby_users() is returning an empty list.

**Comment by charliewolf** [comment]
Resolved in latest `master`
