### ISSUE TITLE
same ping_time now

### ISSUE THREAD

**Issue by ttse007** [charliewolf/pynder#141]
Seems like they changed the API and it always return the same ping_time now? Maybe it is worth noting.

Edit: Maybe it is to do with this Tinder Online that they are launching. Tidying up the API.

**Comment by sof123** [comment]
Came in to report the same :(

**Comment by ttse007** [comment]
I see a "last_fetch_time" from the /user/recs but nothing if you just request /user/id. Where did you see "last_activity_date"?

**Comment by sof123** [comment]
last_activity_date is at /updates. it was actually there before and it does not seem to be related to just being active. probably for messages, liking messages, matching aka visible activity

**Comment by halalfood** [comment]
what does ping_time do?

**Comment by Jonovono** [comment]
So did Tinder they remove the last active date from the api now? I figured they would eventually since they don't show it in the app anymore.

**Comment by modulebaan** [comment]
To avoid tracking users I guess...

**Comment by ttse007** [comment]
I used it to track bots mainly, because they were usually inactive profiles :(.

**Comment by modulebaan** [comment]
Nowadays, bots almost send first a message containing the same text (which I have encountered). Maybe you can filter on that?

**Comment by charliewolf** [comment]
Tinder likely deprecated this feature but kept the field in for old clients.
