### ISSUE TITLE
Can a ton of requests lead to a 403 error?

### ISSUE THREAD

**Issue by halalfood** [charliewolf/pynder#159]
result = self._session.request(method, self._url( 

^this keeps returning a 403 response.
Admittedly I have been running a ton of requests and Tinder has force closed remote connection. Is it possible that Tinder has an API limit for likes? This normally works while running Boost from the app but today it did not.

Could it be Tinder has implemented a timeout for certain API requests?

**Comment by brenly** [comment]
Tinder does in fact has a limit on the number of Likes you can dispense per day.

**Comment by brenly** [comment]
I believe I saw bots weaving around a while back that seem to have found work arounds and aggresively dispensed Super Likes but I am under the impression that is strictly extracurricular knowledge.

**Comment by halalfood** [comment]
The problem is I have not reached that limit on the app on my phone but it still hits a 403 error when using pynder from desktop.

**Comment by halalfood** [comment]
something simple like this and it still returns a 403 when it should not:

> requests.packages.urllib3.disable_warnings()
>
> session = pynder.Session(FACEBOOK_ID, FACEBOOK_AUTH_TOKEN)
> 
> 
> def handle_likes():
>     while True:
>         try:
>             users = session.nearby_users()
>             for u in users:
>                 u.like()
>                 print('[' + str(datetime.datetime.now()) + ']' + ' ' + 'Liked ' + u.name)
>         except ValueError:
>             return
>         except pynder.errors.RequestError:
>             return
>         except KeyError:
>             return
> 
> 
> while True:
>         handle_likes()
>         print('[' + str(datetime.datetime.now()) + ']' + ' ' + 'stopping for 10 minutes')
>         time.sleep(600)

**Comment by halalfood** [comment]
resolved this actually >> not sure why but looked at the example and copied this 

session = pynder.Session(facebook_id=FACEBOOK_ID, facebook_token=FACEBOOK_AUTH_TOKEN)
