### ISSUE TITLE
Multiple questions about proxy interaction

### ISSUE THREAD

**Issue by kkai4u** [charliewolf/pynder#162]
Hello,  
I had multiple questions about the api.
Q.1:
Correct me if i'm wrong,` but the api uses the proxy only when authenticating with the Tinder server and not when communicating with it after that. 

Q2.:
Also how would I know if the proxy is not responding correctly or there is an issue with the account?

Q3:
Another question, do I pass the proxy as
`
session=pynder.Session(facebook_id=XXX,facebook_token=XXX,proxies={'http':'PROXY HERE'}
`
Thank you for the wonderful api!

**Comment by GreatOldOne** [comment]
Q1:
Proxies are used for every request, at least with the lastest version.

Q2:
HTTP error codes. Tinder should give you 400 or 403 for invalid Tinder tokens.
Proxy can be managed with HTTP error codes related to proxy (such as authentication) and socket related errors, such as refused and timeout.

Q3:
Same as the Requests module.
http://docs.python-requests.org/en/master/user/advanced/#proxies
