### ISSUE TITLE
Being banned by Facebook

### ISSUE THREAD

**Issue by enric1994** [charliewolf/pynder#174]
Hey guys!
After being banned multiple times by facebook, i would like to share some possible reasons:
1-Uninstall the app from your mobile and keep accessing to tinder API.
2-Request the token 1 time every minute using [this script.](https://github.com/charliewolf/pynder/issues/114)
3-Request the session every 3 seconds.

Note that when FB blocks you, you get a "proxy error" or "couldn't authenticate". In addition, when you open the app, FB force you to upload a photo of your face to validate you are not a robot (they never validate my photos).

Someone get banned by FB? Which is the reason (1,2 or 3) why I get banned?

Thanks in advance.

**Comment by nurtia** [comment]
Happened to me, when requesting token and session twice a day. (app installed)
