### ISSUE TITLE
Stucking in loop

### ISSUE THREAD

**Issue by heylamourding** [charliewolf/pynder#185]
>>> import itertools
>>> import pynder
>>> session = pynder.Session(FB_token)
>>> users = session.nearby_users()
>>> for user in itertools.islice(users, 5):
...     print user.like()

Stucking in loop. Is there any wrong? Thanks!

**Comment by derblub** [comment]
This is not the right place to help you learn coding.  
If you don't know how to debug a for-loop, you're going to have a hard time.

**Comment by charliewolf** [comment]
maybe a little more blunt than I might have put it but @derblub is on point here
