### ISSUE TITLE
Add like_all() method to session

### ISSUE THREAD

**Issue by charlierm** [charliewolf/pynder#2]
It would be useful to implement 'like all' functionality. It goes beyond the remit of a simple client but IMO would be handy.

Perhaps add all likes onto a queue then have several consuming threads to like them?

Not sure on tinder rate limiting.

**Comment by charliewolf** [comment]
Tinder does rate limiting and from my understanding even bearing that in mind it uses some sort of (unknown) algorithm that punishes people who like too many people. I've seen some clients battle this by randomly disliking every X person. I think that's something that should be under the purview of the person writing the final client code though as there are other ways you could be filtering, you may or may not want to do the random dislike, etc. I don't like the idea of pynder making the decision for the user.
