### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by tushar-asodariya** [charliewolf/pynder#208]
**CODE**
session = pynder.Session(facebook_id=fb_user_id,facebook_token=fb_access_token)

**ERROR**

JSONDecodeError                           Traceback (most recent call last)
<ipython-input-39-14e48b4a1845> in <module>
     13 print(fb_user_id)
     14 
---> 15 session = pynder.Session(facebook_id=fb_user_id,facebook_token=fb_access_token)
     16 
     17 while True:

C:\ProgramData\Anaconda3\lib\site-packages\pynder\session.py in __init__(self, facebook_token, XAuthToken, proxies, facebook_id)
     16         # perform authentication
     17         if XAuthToken is None:
---> 18             self._api.auth(facebook_id, facebook_token)
     19 
     20     @cached_property

C:\ProgramData\Anaconda3\lib\site-packages\pynder\api.py in auth(self, facebook_id, facebook_token)
     21         data = {"facebook_id": str(facebook_id), "facebook_token": facebook_token}
     22         result = self._session.post(
---> 23             self._url('/auth'), json=data, proxies=self._proxies).json()
     24         if 'token' not in result:
     25             raise errors.RequestError("Couldn't authenticate")

C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py in json(self, **kwargs)
    895                     # used.
    896                     pass
--> 897         return complexjson.loads(self.text, **kwargs)
    898 
    899     @property

C:\ProgramData\Anaconda3\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

C:\ProgramData\Anaconda3\lib\json\decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

C:\ProgramData\Anaconda3\lib\json\decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**I have already upgraded my pynder**
based on issue #101

**Comment by MMcintire96** [comment]
The facebook authentication method seems to be failing. You can authorize with sms but it will take some work. 

To get you sms_auth token check out https://github.com/fbessez/Tinder/blob/master/phone_auth_token.py

In pynder you can change the headers to this.
```python
tinder_token = "YOUR_SMS_TINDER_TOKEN"
headers = {
    'app_version': '6.9.4',
    'platform': 'ios',
    'content-type': 'application/json',
    'User-agent': 'Tinder/7.5.3 (iPohone; iOS 10.3.2; Scale/2.00)',
    'X-Auth-Token': tinder_token,
}
```

And this should work as far as I am aware.

**Comment by ghost** [comment]
Didnt work for me? anybody tried something else?

**Comment by MMcintire96** [comment]
I recreated a similar version of this API  with SMS auth, it works for me. Maybe try out my API but I would think those auth headers would work as long as your account is linked to your phone number. 

https://github.com/MMcintire96/python_TinderAPI
