### ISSUE TITLE
accident

### ISSUE THREAD

**Issue by nang-dev** [charliewolf/pynder#214]
when running all_matches(), it returns a 401 error. 

this can be fixed by editing the url in the function to:

url = config.host + '/v2/matches?count?50'

which will give you the 50 most recent matches

**Comment by nang149** [comment]
alternatively, we can make the count a parameter and change all_matches() to:

def all_matches(count):
    try:
        url = config.host + '/v2/matches?count=' + count
        r = requests.get(url, headers=headers)
        return r.json()
    except requests.exceptions.RequestException as e:
        print("Something went wrong. Could not get your match info:", e)

**Comment by nang-dev** [comment]
meant to post on tinder API github
