### ISSUE TITLE
Doesn't appear to like matches

### ISSUE THREAD

**Issue by komposure** [charliewolf/pynder#29]
Firstly the code I've written (in case there's something wrong with it, and also if it this helps somebody who does use this API successfully):

```
import pynder
import time
import random
import json

def getMaxSessionTime():
    return time.time() + round(random.uniform(60*60*2,60*60*3), 1)

def getWaitTime():
    return round(random.uniform(60*30,60*60*1), 1)

FBTOKEN = "CAAG..."
FBID = "101..."

locationLat = 51.507300
locationLong = -0.127550

uncommonUsers = []
commonUsers = []
session = pynder.Session(FBID, FBTOKEN)
matches = session.matches()
count = 0

while True:
    startTime = time.time()
    maxSessionTime = getMaxSessionTime()
    waitTime = getWaitTime()

    session = pynder.Session(FBID, FBTOKEN)

    print "Setting location to " + str(locationLat) + ", " + str(locationLong) + "."
    print "Change your location here: http://www.latlong.net/"
    session.update_location(locationLat, locationLong)
    print ""

    while time.time() < maxSessionTime:
        print "####################"
        print ""
        print "Getting new matches..."
        print ""
        print "####################"
        print ""

        users = session.nearby_users()
        currentMatches = session.matches()
        matchDifferences = list(set(map(str, currentMatches)) - set(map(str, matches)))

        if matchDifferences != []:
            print "[[[[[ New matches! ]]]]]"
            for differentMatch in matchDifferences:
                print "Name:"
                print differentMatch
                print ""

        if not users:
            noUsersTime = getWaitTime()
            print "Ran out of people to find! Delaying for " + str(noUsersTime)
            time.sleep(noUsersTime)
        else:
            for user in users:
                print "####################"
                print ""
                print "Current like count this session: " + str(count)
                print ""
                print "Name: " + user.name
                print "Age: " + str(user.age) + " (date of birth: " + str(user.birth_date) + ")"
                print ""

                connections = user.common_connections
                if connections == []:
                    print "No mutual friends - liked."
                    # uncommonUsers.extend(user)

                    count += 1

                    if (user.like()):
                        print " +++ User has matched you! +++"
                    else:
                        print " --- User hasn't matched (yet) ---"
                else:
                    print "Mutual friends - added to common matches."
                    commonUsers.append(user)
                print ""

                delay = round(random.uniform(0.7,1.7), 10)
                time.sleep(delay)

    print "Max session time reached - delaying for " + str(waitTime) + " seconds."
time.sleep(waitTime)
```

After reaching 1,800 likes I decided to give the bot a break. This was done on a fresh Tinder profile. After 3 days, no matches came through. I decided to do ~100 swipes manually. Lo and behold, I got 2 matches, within the hour!

Are we sure that the API is still functioning? If so, is there anything wrong with the code I've posted?

**Comment by charliewolf** [comment]
What time did you do the bot vs the manual?

**Comment by komposure** [comment]
Friday ~10:00-15:00 (GMT) for the bot, and manually Sunday ~10:00-15:00, although the sheer size difference of match requests surprises me that it doesn't work. I've also tested it with a profile that had pictures that reeeally should get responses, as it was a female. Again, no responses! I would've swiped right...

**Comment by charliewolf** [comment]
I don't have time to debug this right now but yeah it sounds like they have some heuristics they are using to detect this.

**Comment by komposure** [comment]
Anything I can do to help? I am currently using Charles (the software) to debug the output of the app, is this the right way to go?

**Comment by charliewolf** [comment]
Yeah the best next step would be compare the requests from Charles for the app vs pynder and look for discrepancies

**Comment by komposure** [comment]
I'll take a look later this evening and post notable differences back here. Maybe a pull request if I'm confident enough with Python! Thanks for your help again

**Comment by charliewolf** [comment]
Sure, that would be very helpful, thanks!

**Comment by emersonsoares** [comment]
Same problem here.

**Comment by charliewolf** [comment]
@komposure Were you able to do that packet capture?

**Comment by komposure** [comment]
@charliewolf Not just yet I'm afraid, completely slipped my mind! Will try to do that tonight - noob warning at all of this developer stuff though, so it may be a case of me dumping the logs as a Gist if I can't figure it out :sweat_smile:

**Comment by vyscond** [comment]
Indeed. We can find the people around but not like them. :(

**Comment by cmertin** [comment]
@komposure, it seems to work for me. I even used your code.

**Comment by charliewolf** [comment]
If someone can post logs showing the difference I'm happy to investigate this but until then I'm closing this as not reproducable
