### ISSUE TITLE
Adding workplace and education?

### ISSUE THREAD

**Issue by mcfoton** [charliewolf/pynder#33]
Hi and thank you for this awesome wrapper!
Recent Tinder update added workplace and education. Do you plan adding those? If not, where should I start?

**Comment by charliewolf** [comment]
The best place to start would be to use [Charles like in this blog](http://www.joelotter.com/2015/05/17/dj-khaled-tinder-bot.html) to capture traffic while you change yours and then post the results here so we can see what API calls they make

**Comment by mcfoton** [comment]
Success! This info is already sent to us. I was able to access it after adding two last keywords:
```
SIMPLE_FIELDS = "name bio birth_date ping_time jobs schools".split(" ")
```
to https://github.com/charliewolf/pynder/blob/master/pynder/models/user.py#L13
but it's not a final solution as the format is a bit clumsy:

```
>>> for user in users
>>>    print user.jobs
[{u'company': {u'name': u'\u0417\u0410\u041e "\u0424\u0418\u041d\u0410\u041c"'}}]
[]
[]
[]
[{u'company': {u'name': u'Itella Connexions'}, u'title': {u'name': u'Account Manager'}}]
```

At this point I'm not sure how to implement it right :( By "right" I mean i.e.
user.job_company
user.job_title
user.school

**Comment by charliewolf** [comment]
Try user.jobs and user.schools in master

**Comment by mcfoton** [comment]
@charliewolf  Thank you!
