### ISSUE TITLE
Multiple Requests when calling session.matches()?

### ISSUE THREAD

**Issue by Jonovono** [charliewolf/pynder#41]
Hi. I noticed getting my matches was taking a long time (1.5 minutes or so). That seemed strange.

I added some print statements to the _request:

        def _request(self, method, url, data={}):
        if not hasattr(self, '_token'):
            raise errors.InitializationError
        result = self._session.request(method, self._url(url), data=json.dumps(data), proxies=self._proxies)
        print "stat ", result.status_code
        while result.status_code == 429:
            blocker = threading.Event()
            blocker.wait(0.01)
            result = self._session.request(method, self._url(url), data=data, proxies=self._proxies)
        if result.status_code != 200:
            raise errors.RequestError(result.status_code)
        return result.json()

And in the logs I see

    stat  200
    stat  200
    stat  200
    stat  200
    stat  200
    stat  200
    stat  200

Is there a reason for this? Is it a bug?

**Comment by charliewolf** [comment]
Sounds like it. Can you change 
`    print "stat ", result.status_code`
to 
`    print "stat ", result.status_code, method, url`
and post results?

**Comment by Jonovono** [comment]
@charliewolf Ya :)

So what it's doing is for each match also calling /user_info/<id> for each match.

I'll have to figure something out. I am running on appengine which seems to not be liking 60s responses or something
