### ISSUE TITLE
Failing to authenticate

### ISSUE THREAD

**Issue by jlfosternz** [charliewolf/pynder#49]
My apologies if I'm doing something stupid here, but I'm an R guy and a newb with Python. I seem to have everything setup right with the pynder module, but for some reason I can't authenticate.

I'm getting my FB Token from a connection I setup in R (and my FB ID), and copied them over to python as fbid and fbtoken. But when I try to authenticate I get the following:

```
sess=pynder.Session(fbid,fbtoken)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pynder-0.0.10-py2.7.egg/pynder/session.py", line 13, in __init__
    self._api.auth(facebook_id, facebook_token)
  File "/Library/Python/2.7/site-packages/pynder-0.0.10-py2.7.egg/pynder/api.py", line 27, in auth
    raise errors.RequestError("Couldn't authenticate")
pynder.errors.RequestError: Couldn't authenticate
```

I've verified the token I'm using and the ID, so I'm just not sure what I'm doing wrong here. Any suggestions?

Thanks for any help you can give!

**Comment by vexin217** [comment]
I am using this link

`https://www.facebook.com/dialog/oauth?client_id=464891386855067&redirect_uri=https://www.facebook.com/connect/login_success.html&scope=basic_info,email,public_profile,user_about_me,user_activities,user_birthday,user_education_history,user_friends,user_interests,user_likes,user_location,user_photos,user_relationship_details&response_type=token`

And I manually copy the token found in the `location` variable (Chrome DevTools). It works just fine.

**Comment by jlfosternz** [comment]
Ahh, that did it. I guess the token I get with facebook's API must behave differently. Thanks for the help mate, and great tool!
