### ISSUE TITLE
session.matches() returns an empty array

### ISSUE THREAD

**Issue by modulebaan** [charliewolf/pynder#54]
I have a match in the original Tinder Android app but when I call in Tinder session.matches() it returns an empty string.

My code:
    session = pynder.Session('ID', 'TOKEN)        
    matches = session.matches()
    print matches    

What do I wrong?

**Comment by charliewolf** [comment]
@modulebaan Yeah the Amazon app is fairly broken and lags way behind the Play store version

**Comment by charliewolf** [comment]
@modulebaan: I use @microg/GmsCore to run on a play services-less device. Works pretty well, if that's an option for you.

**Comment by modulebaan** [comment]
Aliendalvik (the Android runtime) doesn't support microg/GmsCore... A native Tinder app is even better since it won't use a lot of resources of the CPU and the RAM
