### ISSUE TITLE
wrong likes_remaining

### ISSUE THREAD

**Issue by modulebaan** [charliewolf/pynder#55]
If I run the example of Pynder: like_5_users.py (https://github.com/charliewolf/pynder/blob/master/examples/like_5_users.py) I always get the result 'false' for every user.like(). Since it returns 'false' I guess the person isn't liked?

Also the function 'likes_remaining' always returns 100, even if I like some people with the Android app version. I added it to the example with this line:
print session.likes_remaining

**Comment by charliewolf** [comment]
false is correct. It only returns true if they have already liked you. `likes_remaining` sounds like a bug though.

**Comment by modulebaan** [comment]
Oh alright, then 'likes_remaining' is the problem.
I don't know what the bug could be... that piece of data should be in '/meta' and that's what Pynder calls...

**Comment by simion96** [comment]
@modulebaan This is how the tinder API works - there is no way to change that. Unless we knew exactly how many swipes you were allowed a day and then do a manual counter on the client side, but it sounds too troublesome for not much improvement

**Comment by tobwen** [comment]
likes_remaining always returns 100, if you've got Tinder Plus.
