### ISSUE TITLE
Crash when no common_conections found

### ISSUE THREAD

**Issue by divisiondeariza** [charliewolf/pynder#59]
Program crashed when i did this with a facebook profile without friends (thus, without common friends):

``` python
token = "ANYTOKEN123"
tinder_id = "1234567890"
session = pynder.Session(tinder_id, token)
users = session.nearby_users()    
for user in users:
   print user.common_connections
``` 

this is the error:

``` bash
Traceback (most recent call last):
(...)
    print user.common_connections
  File "/.../pynder/models/user.py", line 54, in common_connections
    return [p for p in self._data['common_connections']]
KeyError: 'common_connections'
```

I guess common_connections should be populated as self.jobs or self.schools in users model, i would do by myself but i couldn't run the tests and i don't wanna break something accidentally :(

Have a nice day :)

**Comment by charliewolf** [comment]
Fixed in #60
