### ISSUE TITLE
Issue with – session.matches()

### ISSUE THREAD

**Issue by SHABINTHEGREAT** [charliewolf/pynder#61]
Issue with – **session.matches()**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pynder/session.py", line 26, in matches
    return [models.Match(m, self) for m in self._api.matches()]
  File "/Library/Python/2.7/site-packages/pynder/models/user.py", line 118, in __init__
    self.user = User(user_data, _session)
  File "/Library/Python/2.7/site-packages/pynder/models/user.py", line 23, in __init__
    self.jobs.extend(["%s @ %s" % (job["company"]["name"], job["title"]["name"]) for job in data['jobs'] if 'title' in job])
KeyError: 'company'
```
**Q:** How to resolve this?

Also **session.nearby_users()** returns a null list, even when there are matches on the Tinder App (on iOS).

**Comment by SHABINTHEGREAT** [comment]
Update:
Commenting **line 23** in _**pynder/models/user.py**_ made it work somewhat without any errors coming up.

But that does not seem like the right solution. Please advise and help.

**Comment by charliewolf** [comment]
Are you using latest git master?

**Comment by SHABINTHEGREAT** [comment]
The latest version available from **pip** is being used.
**pynder-0.0.9**.dist-info

`pip search pynder`
`pynder     - A client for the tinder api`
**`  INSTALLED: 0.0.9 (latest)`**

Is that the latest version?
Also, it is being used after **commenting line 23** in **_pynder/models/user.py_** which makes it work somewhat without any errors coming up.

**Comment by charliewolf** [comment]
First validate on git master:
`pip install git+https://github.com/charliewolf/pynder#egg=pynder`

**Comment by SHABINTHEGREAT** [comment]
`pip install git+https://github.com/charliewolf/pynder#egg=pynder`

`Requirement already satisfied (use --upgrade to upgrade): pynder from git+https://github.com/charliewolf/pynder#egg=pynder in /Library/Python/2.7/site-packages`
`Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pynder)`
`Requirement already satisfied (use --upgrade to upgrade): requests in /Library/Python/2.7/site-packages (from pynder)`


That is the response! Since I am new to python & pip, you can interpret and let me know if everything is proper.

**Comment by charliewolf** [comment]
ah, you really shouldn't install globally (this is what virtualenvs are for).
but if you're determined to you can run `pip install --upgrade --force-reinstall git+https://github.com/charliewolf/pynder#egg=pynder`

**Comment by SHABINTHEGREAT** [comment]
Installed and the new results are:
`pip search pynder`
`pynder     - A client for the tinder api`
`  INSTALLED: 0.0.10`
`  LATEST:    0.0.9`


> you really shouldn't install globally (this is what virtualenvs are for)

Since I am new to python & pip, ....
Thank you, I shall read into virtualenvs.

**Comment by charliewolf** [comment]
can you see if you have the same issue now?

**Comment by SHABINTHEGREAT** [comment]
Tried running the application _once_ and it **worked without errors** _(line 23 in pynder/models/user.py)_.

**Thank you, Mr. Wolf!** I shall try again and see if the error comes up, and shall update this thread soon.

**Comment by SHABINTHEGREAT** [comment]
**Problem Solved**
The Pynder module now **works** without the above issue anymore.

**[Thank you, Mr. Wolf!](http://rlv.zcache.com/colorful_barcode_thank_you_postcard-ra816b15cdff64e7481dc025b81508d43_vgbaq_8byvr_512.jpg)**
Your solutions were the correct and perfect. And you have been very prompt, precise and absolutely helpful. 🎀

**Comment by charliewolf** [comment]
I have never received a thank you card via github before, so this is great.

**Comment by SHABINTHEGREAT** [comment]
There is always a first time for everything. Hopefully, may it not be the last. 😇
