### ISSUE TITLE
Match Properties & Attributes – Not working

### ISSUE THREAD

**Issue by SHABINTHEGREAT** [charliewolf/pynder#62]
> For your list of matches, they will have the same attributes as above _(—README.rst)_

**The properties/attributes from `session.nearby_users()` are not working for the `session.matches()`**
```
users = session.nearby_users()
matches = session.matches()

u = users[n]
m = matches[n]
```

`u.name` **works**.
`m.name` does **not work**.

Similarly for other properties and parameters – they **work for `u` but not for `m`**.

Can you please help to clarify or resolve the difference between the two? And **how the users properties can be found for the matches too?**

Thank you, very much.

**Comment by charliewolf** [comment]
Try `m.user.name`

**Comment by SHABINTHEGREAT** [comment]
Perfect and thank you, Mr. Wolf. That makes it work.

Just a question, out of curiosity: Why not make those properties directly accessible with **m.name** just like in **u.name** without adding **m.user.name** since all `matches[n]` seem to have the same user properties just as in `users[n]`?

**Comment by charliewolf** [comment]
@SHABINTHEGREAT I originally designed it that way (the way you're describing) and someone else changed it to the way it is currently. I can't recall why but it seemed like a good idea at the time based on their reasoning. I think perhaps Tinder has match IDs and user IDs separately.

**Comment by SHABINTHEGREAT** [comment]
Thank you for explaining. This makes sense: 
> perhaps Tinder has match IDs and user IDs separately

My intuitions might be wrong, but it was intuitive to use **m.name** and **u.name** format due to the consistency in the pattern.
