### ISSUE TITLE
Difference Between session.matches() and api.updates()

### ISSUE THREAD

**Issue by SHABINTHEGREAT** [charliewolf/pynder#67]
**_To Mr. Wolf_:**

What is the difference between
**`session.matches()`**
_and_
**`session._api.updates()`**

Both seem to be downloading vast amount of data from the tinder server. Both also seem to have the list of messages and other data.
What is the difference between the two? What is the pupose of both?

**Comment by charliewolf** [comment]
`_api` methods are meant to be used internally not directly by end users.

**Comment by SHABINTHEGREAT** [comment]
What is the difference between the two? What is the pupose of both?
Both seem to be downloading vast amount of data from the tinder server. Both also seem to have the list of messages and other data.
But the **sizes of those datasets downloaded** seem to be much different for the two!
Hence, the question out of curiosity – because session.matches() times out on slower connections, but the api.updates() does not, and still seem to download the latest messages as well!

**Comment by SHABINTHEGREAT** [comment]
**—???—**
