### ISSUE TITLE
How do I get the facebook_auth_token?

### ISSUE THREAD

**Issue by frmsaul** [charliewolf/pynder#69]
Should I just produce it using the _Graph API Explorer_?

What kind of permissions do I need?

**Comment by modulebaan** [comment]
You can get an auth code with this link:

https://www.facebook.com/dialog/oauth?client_id=464891386855067&redirect_uri=https://www.facebook.com/connect/login_success.html&scope=basic_info,email,public_profile,user_about_me,user_activities,user_birthday,user_education_history,user_friends,user_interests,user_likes,user_location,user_photos,user_relationship_details&response_type=token

This link will give an token when you are redirected.

**Comment by frmsaul** [comment]
It worked!

Is there a way to extend the token or ask for request a longer-lasting token?

Is the **client_id** specific for tinder?

**Comment by modulebaan** [comment]
I would love to find a way to get a long access token but you need the APP_SECRET token from Tinder. I didn't find that yet...

**Comment by charliewolf** [comment]
Some people have found a long token by using Charles and intercepting what the actual Tinder app on their phone is doing

**Comment by modulebaan** [comment]
I don't have an Android Phone, only a Jolla Phone with Sailfish OS. I build a Sailfish App based on Pynder to use Tinder on Sailfish OS. The only thing I miss is the APP_SECRET code and then it's easy to get an long access token.

**Comment by frmsaul** [comment]
This has stopped working.
Do you know if Facebook did anything to block it? 


Getting the following error message:

URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.

**Comment by modulebaan** [comment]
Ignore it, if you have cookies enabled and try this again it works ;)

**Comment by frmsaul** [comment]
It doesn't work for me.
I'v opened a new issue with more details, please take a look:

[Issue](https://github.com/charliewolf/pynder/issues/99)
