### ISSUE TITLE
Using too much memory for getting all the matches

### ISSUE THREAD

**Issue by Crongz** [charliewolf/pynder#70]
# `session.matches()` uses too much memory when your tinerbot has too much matches.

same issue as https://github.com/charliewolf/pynder/issues/64

**Comment by charliewolf** [comment]
do you have more details on this?

**Comment by Crongz** [comment]
When the tinder bot has a lot of matches & messages, it uses a lot of memory for getting all the data.

**Comment by Crongz** [comment]
I made a PR about using generator to reduce some memory usage.

**Comment by SHABINTHEGREAT** [comment]
What is the difference happening here: [Link](https://github.com/charliewolf/pynder/pull/71/commits/01c605d887be087ff3ada4922a744d29d01d869f)

Please explain!

**Comment by charliewolf** [comment]
@SHABINTHEGREAT It turns it from a list comprehension to a generator expression

**Comment by SHABINTHEGREAT** [comment]
@charliewolf
How does that reduce memory usage, especially when the data is the same?

**Comment by charliewolf** [comment]
@SHABINTHEGREAT because it iterates one by one rather than loading the whole array into memory.

**Comment by h-2-0** [comment]
@Crongz 

Thanks. This is great!

**Comment by charliewolf** [comment]
Resolved in  3b898a024
