### ISSUE TITLE
Last activity date 

### ISSUE THREAD

**Issue by twon23** [charliewolf/pynder#72]
I've noticed there does not seem to be a way to post last activity date so you can retrieve data from a certain time. This would be good to check for matches after a certain date/time, new messages and use less bandwidth as it would only pull the new data.

Any one else interested in this? And thoughts of integrating it?

Here is some proposed code:
https://github.com/twon23/pynder/commit/2a41214044f1f0b7dee20f3658ac074f428578f5

**Comment by charliewolf** [comment]
Can you make a PR for this?
