### ISSUE TITLE
no longer able to get nearby users

### ISSUE THREAD

**Issue by flyfj** [charliewolf/pynder#85]
so I used the api to like users, some errors occurred during the process but got caught and continued. but now I can no longer get nearby_users(), even on my tinder app, it hangs in searching for users. anyone knows how to deal with this?

**Comment by h-2-0** [comment]
I have no problems at all both using pynder or mobile app

**Comment by h-2-0** [comment]
You probably run out of users available in your area. Increase your distance search range.

**Comment by flyfj** [comment]
@h-2-0 thank you. i just checked and it starts to work again.
