### ISSUE TITLE
How do you know when nearby_users() has recomendations again (once exhausted)

### ISSUE THREAD

**Issue by h-2-0** [charliewolf/pynder#86]
Once you exhausted all likes from session.nearby_user(), how do I know when you are available to like again? I know it's 12 hours after you finished them (in case of a free account). But how do you get the time left to like again?

**Comment by h-2-0** [comment]
Forget about it. Found it!

`can_like_in`

**Comment by halalfood** [comment]
what does it mean if can_like_in is negative but recs is returning exhausted @h-2-0 ?

**Comment by h-2-0** [comment]
@halalfood 
If I recall correctly `can_like_in` returns negative when you run out of likes (i.e. in a non-Tinder Plus account). 

Also, I don't see how `recs` is related with the above. Recs is a group of users (recommendations) Tinder shows you based on your swiping behaviour (and how other users swipe to you).
